=== developmentseed/cogeo-watchbot/scripts/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "name": "Watchbot specification",
	"type": "object",
	"properties": {
		"sources": {
            "description": "List of files to convert to COG",
			"type": "array"
        },
        "profile_name": {
            "description": "rio-cogeo profile name",
            "type": "string",
            "enum": ["jpeg", "webp", "zstd", "lzw", "deflate", "packbits", "raw"]
        },
        "profile_options": {
            "description": "Dictionary of options to extend the cog profile",
            "type": "object"
        },
        "options": {
            "description": "Dictionary of options to pass to rio_cogeo.cogeo.cog_translate function",
            "type": "object"  
        },
        "mosaicid": {
            "description": "A mosaic id where to happend new data",
            "type": "string",
            "pattern": "^[0-9A-Fa-f]{56}$"
        },
        "copy_valid_cog": {
            "description": "Boolean indicating to copy COG if they are valid",
            "type": "boolean"
        }
	},
	"required": [
		"sources"
	]
}

=== developmentseed/cogeo-watchbot/examples/spacenet_moscow.json
{"sources":["https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip0.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip1.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip10.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip100.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip101.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip102.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip103.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip104.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip105.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip106.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip107.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip108.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip109.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip11.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip110.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip111.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip112.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip113.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip114.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip115.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip116.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip117.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip118.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip119.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip12.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip120.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip121.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip122.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip123.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip124.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip125.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip126.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip127.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip128.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip129.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip13.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip130.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip131.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip132.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip133.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip134.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip135.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip136.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip137.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip138.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip139.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip14.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip140.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip141.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip142.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip143.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip144.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip145.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip146.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip147.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip148.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip149.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip15.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip150.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip151.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip152.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip153.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip154.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip155.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip156.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip157.tif","https://spacenet-dataset.s3.amazonaws.com/spacenet/SN5_roads/test_public/AOI_7_Moscow/PS-RGB/SN5_roads_test_public_AOI_7_Moscow_PS-RGB_chip158.tif","https://spacen
